version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      include: scope
      update-types:
        - "version-update:semver"
        - "version-update:all"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"